#Преобразование входных данных
ROLLING_MEAN: False
EXP_SMOOTH: False
DOUBLE_EXP_SMOOTH: False
ROLLING_MEAN_WINDOW: 32

# Входные параметры
KKS: 'kks_with_groups_Sochi_last.csv'  #Файл с группами
WEIGHTS: 'SOCHI/weights_new'
SCALER: 'SOCHI/scaler'
SCALER_LOSS: 'SOCHI/scaler_loss'
SCALER_LOSS_NAME: 'cdf'

# Подключение к БД
IP_BD: '10.23.0.87'
USER: 'default'
PASSWORD: 'asdf'


# Параметры алгоритма
POWER_ID: 'Sochi2.GT.AM.20CFA10CE001-AM.Q'
POWER_LIMIT: 19
NUM_GROUPS: 12 #Количество групп
LAG: 1 #Значение лага обучения
QUERY_DF: "SELECT * FROM slices_play order by timestamp desc limit 1"
ZERO_PREV_VAL: True #зануляет значения target_value если мощность меньше нуля

TRAIN_LEN_FORECAST: 30
LEN_FORECAST: 5
WINDOW_SIZE: 5
TRESHOLD_ANOMALY: 90 
CONTINUE_COUNT: 10

TIME_BETWEEN_PREDICT: 30 #время между предсказаниями
