#Преобразование входных данных
ROLLING_MEAN: True
EXP_SMOOTH: False
DOUBLE_EXP_SMOOTH: False
ROLLING_MEAN_WINDOW: 32

# Входные параметры
KKS: '/home/art/InControl/Offline_LSTM/SOCHI/kks_with_groups.csv' #Файл с группами
WEIGHTS: 'SOCHI/weights'
SCALER: 'SOCHI/scaler'

CSV_SAVE_RESULT_PREDICT: 'csv_predict/predict'
CSV_SAVE_RESULT_LOSS: 'csv_predict/loss'
CSV_DATA: 'csv_data/'
JSON_DATA: 'json_interval/'
SCALER_LOSS: 'scaler_loss/'
# TEST_FILE: SELECT * FROM slices order by timestamp limit 1
TEST_FILE: '/home/art/Downloads/slices(3).csv'


# Параметры алгоритма
POWER_ID: 'Sochi2.GT.AM.20CFA10CE001-AM.Q'
POWER_LIMIT: 19
POWER_FILL: 'zeroes'
NUM_GROUPS: 12 #Количество групп
LAG: 1 #Значение лага обучения
MEAN_NAN: False
DROP_NAN: True
AUTO_DROP_LIST: False # удаление датчиков нулевой группы
DROP_LIST: [] #удаление датчиков из отчета CSV


# COUNT_ANOMALY: 300
ROLLING_MEAN_LOSS: 128
# ANOMALY_TRESHOLD: 0.8
LEN_LONG_ANOMALY: 800
LEN_SHORT_ANOMALY: 300
COUNT_CONTINUE_SHORT: 10
COUNT_CONTINUE_LONG: 15
SHORT_TRESHOLD: 98
LONG_TRESHOLD: 97

COUNT_TOP: 3
